### ISSUE TITLE
Incluir serviço do selenium no docker-compose.yaml 

### ISSUE THREAD

**Issue by nitaibezerra** [economiagovbr/Ro-dou#19]
Após as últimas atualizações no [dou_hook.py](https://github.com/economiagovbr/FastETL/commit/b90299458063567f9b44bbc7db83450039c2ad08) o Ro-dou não funciona corretamente sem a inclusão de mais um serviço na stack no docker-compose.yml para rodar o selenium.

A solução é basicamente adicionar este trecho ao `docker-compose.yml`:

``` yaml  
    selenium:
        image: ghcr.io/economiagovbr/selenium:ro-dou
        volumes:
          - /dev/shm:/dev/shm
``` 

Também é preciso esclarecer no README que o ambiente utiliza este serviço extra nas consultas ao DOU.
